// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-cpHYnWDncKWaHeJ_2fa7uMPBMsZoEzI',
    appId: '1:557331099141:web:241ce4055fac6fce8df66c',
    messagingSenderId: '557331099141',
    projectId: 'todo-app-95655',
    authDomain: 'todo-app-95655.firebaseapp.com',
    storageBucket: 'todo-app-95655.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBD_itk3aBzNBJEC3CNUFyppgKEH5V-qI',
    appId: '1:557331099141:android:d45487f25d31cc718df66c',
    messagingSenderId: '557331099141',
    projectId: 'todo-app-95655',
    storageBucket: 'todo-app-95655.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-krjq2oYQyogl7XqFkjD1Chj_VdZGgk',
    appId: '1:557331099141:ios:6cbf75f6b126371f8df66c',
    messagingSenderId: '557331099141',
    projectId: 'todo-app-95655',
    storageBucket: 'todo-app-95655.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP-krjq2oYQyogl7XqFkjD1Chj_VdZGgk',
    appId: '1:557331099141:ios:6cbf75f6b126371f8df66c',
    messagingSenderId: '557331099141',
    projectId: 'todo-app-95655',
    storageBucket: 'todo-app-95655.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-cpHYnWDncKWaHeJ_2fa7uMPBMsZoEzI',
    appId: '1:557331099141:web:895cdc28205c64208df66c',
    messagingSenderId: '557331099141',
    projectId: 'todo-app-95655',
    authDomain: 'todo-app-95655.firebaseapp.com',
    storageBucket: 'todo-app-95655.firebasestorage.app',
  );

}